mysite/chat/urls.py
# chat/urls.py
from django.conf.urls import url
from . import views

app_name = 'chat'

urlpatterns = [
    url(r'^$', views.chatform, name='chatform'),
    url(r'^(?P<room_name>[^/]+)/$', views.room, name='room'),
]

mysite/myapp/urls.py
from django.conf.urls import url
from . import views

app_name = 'myapp'

urlpatterns = [
    # /myapp/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /myapp/
    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    # /myapp/somenumber/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # /myapp/somenumber/
    # url(r'^chat/$', views.Chat.as_view(), name='chat'),
    
    # /myapp/recipe/add/
    url(r'^recipe/add/$', views.RecipeCreate.as_view(), name='recipe_add'),
    
    # /myapp/recipe/number/
    url(r'^recipe/(?P<pk>[0-9]+)/$', views.RecipeUpdate.as_view(), name='update_recipe'),

    # /myapp/recipe/number/delete/
    url(r'^recipe/(?P<pk>[0-9]+)/delete/$', views.RecipeDelete.as_view(), name='delete_recipe'),

    url(r'^$', views.chatform, name='chatform'),
    url(r'^(?P<room_name>[^/]+)/$', views.room, name='room'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    path('chat/', include('chat.urls', namespace='chat')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/chat/models.py
from django.db import models

# Create your models here.

mysite/myapp/models.py
from django.db import models
from django.urls import reverse


class Recipe(models.Model):
    recipe_title = models.CharField(max_length=250)
    category = models.CharField(max_length=500)
    description = models.CharField(max_length=250)
    ingredients = models.CharField(max_length=250)
    instructions = models.CharField(max_length=500)
    alcohol_percentage = models.IntegerField(default=0)
    recipe_logo = models.FileField()
    is_favorite = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('myapp:detail', kwargs={'pk': self.pk})
    def __str__(self):
        return self.recipe_title + ' - ' + self.category

'''

ingredients = models.CharField(max_length=250)
    instructions = models.CharField(max_length=250)

class Mix(Recipe):
    mix_title = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    alcohol_percentage = models.IntegerField(default=0)

    def __str__(self):
        return str(self.mix_title)


class Suggestion(models.Model):
    suggestion_field = models.CharField(max_length=250)

    def __str__(self):
        return self.suggestion_field

class LiquorType(models.Model):
    beers = models.CharField(max_length=250)
    wines = models.CharField(max_length=250)
    mix_drinks = models.CharField(max_lenth=250)

class Beer(models.Model):
    beer_type = models.CharField(max_lenth=250)
    beer_style = models.CharField(max_length=250)
    beer_title = models.CharField(max_length=250)
    beer_brewer = models.CharField(max_length=250)
    beer_country = models.CharField(max_length=250)
    beer_acohol_content = models.CharField(max_length=250)
    beer_description = models.CharField(max_length=250)

class Wine(models.Model):
    wine_type = models.CharField(max_lenth=250)
    wine_style = models.CharField(max_length=250)
    wine_title = models.CharField(max_length=250)
    wine_brewer = models.CharField(max_length=250)
    wine_country = models.CharField(max_length=250)
    wine_acohol_content = models.CharField(max_length=250)
    wine_description = models.CharField(max_length=250)

'''

mysite/myapp/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)


    class Meta:
        model = User
        fields = ['username', 'email', 'password']

mysite/chat/views.py
# chat/views.py
from django.shortcuts import render
from django.utils.safestring import mark_safe
import json

def chatform(request):
    return render(request, 'chatform.html', {})

def room(request, room_name):
    return render(request, 'room.html', {
        'room_name_json': mark_safe(json.dumps(room_name))
    })

mysite/myapp/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import View

from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login

from .models import Recipe
from .forms import UserForm

from django.utils.safestring import mark_safe
import json

class IndexView(generic.ListView):
    template_name = 'index.html'
    context_object_name = 'all_recipes'

    def get_queryset(self):
        return Recipe.objects.all()

class DetailView(generic.DetailView):
    model = Recipe
    template_name = 'detail.html'

class RecipeCreate(CreateView):
    model = Recipe
    fields = ['recipe_title', 'category', 'description', 'ingredients', 'instructions', 'alcohol_percentage', 'recipe_logo']
    template_name = 'recipe_form.html'

class RecipeUpdate(UpdateView):
    model = Recipe
    fields = ['recipe_title', 'category', 'description', 'recipe_logo']

class RecipeDelete(DeleteView):
    model = Recipe
    success_url = reverse_lazy('myapp:index')

#class Chat(generic.DetailView):
#    template_name = "chat.html"

class UserFormView(View):
    form_class = UserForm
    template_name = 'registration_form.html'

    # blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            # clean (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # return user objects if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('myapp:index')
        
        return render(request, self.template_name, {'form': form})

def chatform(request):
    return render(request, 'chatform.html', {})

def room(request, room_name):
    return render(request, 'room.html', {
        'room_name_json': mark_safe(json.dumps(room_name))
    })

mysite/myapp/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Home{% endblock %}</title>

    {% load staticfiles %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>

<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <!--Home-->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'myapp:index' %}">Home</a>
            </div>

            <!--Items-->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'myapp:index' %}">
                            <span class="glyphicon glyphicon-glass" aria-hidden="true"></span>&nbsp; Recipes
                        </a>
                    </li>
		    <!--
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>&nbsp; Forums
                        </a>
                    </li>
		    -->
                    <li class="">
                        <a href="{% url 'chat:chatform' %}">
                            <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>&nbsp; Chat
                        </a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'myapp:recipe_add' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Recipes
                        </a>
                    </li>
                    <li class="">
			    <a href="{% url 'myapp:register' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Register
                        </a>
                    </li>
                </ul>
		<!--
                <form class="navbar-form navbar-right" role="search" method="get" action="#">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value="">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>
		-->
            </div>
        </div>
    </nav>

{% block body %}
{% endblock %}

</body>

</html>

mysite/myapp/templates/chat.html
{% extends 'base.html' %}

{% block body %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br/>
    <input id="room-name-input" style="color:black" type="text" size="100"/><br/>
    <input id="room-name-submit" style="color:black" type="button" value="Enter"/>

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/myapp/chat/' + roomName + '/';
        };
    </script>
</body>
</html>

{% endblock %}

mysite/myapp/templates/chatform.html
{% extends 'base.html' %}

{% block body %}

<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br/>
    <input id="room-name-input" style="color:black" type="text" size="100"/><br/>
    <input id="room-name-submit" style="color:black" type="button" value="Enter"/>

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>
</html>

{% endblock %}

mysite/myapp/templates/detail.html
{% extends 'base.html' %}

{% block title %}Recipe Description{% endblock %}

{% block body %}
<div align="center">
<img src="{{ recipe.recipe_logo.url }}" style="width: 250px;">

<h1>{{ recipe.recipe_title }}</h1>

    <h2>Ingredients</h2>
    <li>{{ recipe.ingredients }}</li>
    <h2>How-To-Mix</h2>
    <p>{{ recipe.instructions }}</p>
    <h2>Alcohol Percentage</h2>
    <p>{{ recipe.alcohol_percentage }} %</p>
</div>
{% endblock %}

mysite/myapp/templates/form_template.html
{% for field in form %}
<style>
        body {
            font-family: Arial, Helvetica, sans-serif;
        }
    
        * {
            box-sizing: border-box;
        }
    
        input[type=text],
        select,
        textarea {
            width: 65%;
            padding: 12px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
            margin-top: 0px;
            margin-bottom: 0px;
            resize: vertical;
        }
    
        input[type=submit] {
            background-color: #4CAF50;
            color: white;
            padding: 12px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }
    
        input[type=submit]:hover {
            background-color: #45a049;
        }
    
        .container {
            max-width: 750px;
            border-radius: 5px;
            padding: 15px;
            margin: auto;
            background-color: #f2f2f2;
        }
    </style>


<font color="black">
    <div class="container">
        <div class="row">
        <div class="form-group">
            <div class="row justify-content-md-center">
                <span class="text-danger small">{{ field.errors }}</span>
            </div>
            <label class="control-label col-sm-3 align-item-center" for="song_title">{{ field.label_tag }}</label>
            <div>{{ field }}</div>
        </div>
    </div>
</div>
</font>
{% endfor %}

mysite/myapp/templates/index.html
{% extends 'base.html' %}
{% block title %}Random Recipes{% endblock %}

{% block body %}
<div class="recipe-container container-fluid">
    <!--Recipe Block-->
    <div class="row">
        <div class="col-sm-12">
            <h3></h3>
        </div>
        {% if all_recipes %}
        {% for recipe in all_recipes %}
        <div class="col-sm-4 col-lg-2">
            <div class="thumbnail">
                <a href="{% url 'myapp:detail' recipe.id %}">
                    <img src="{{ recipe.recipe_logo.url }}" class="img-responsive">
                </a>
                <div class="caption">
                    <h2>{{ recipe.recipe_title }}</h2>
                    <h4>Category: {{ recipe.category }}</h4>
                    <h4>Percentage: {{ recipe.alcohol_percentage }}%</h4>

                    <!--View Recipe-->
                    <a href="{% url 'myapp:detail' recipe.id %}" class="btn btn-primary btn-sm" role="button">ViewRecipe</a>

                    <!--Delete Recipe-->
                    <form action="{% url 'myapp:delete_recipe' recipe.id %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="recipe_id" value="{{ recipe.id }}" />
                        <button type="submit" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    </form>

                    <!-- Favorite Album -->
                    <a href="#" class="btn btn-default btn-sm btn-favorite" role="button">
                            <span class="glyphicon glyphicon-star"></span>
                    </a>
                </div>
            </div>
        </div>
        {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
        {% endfor %}
        {% else %}
        <div class="col-sm-12">
            <br>
            <a href="{#}">
                <button type="button" class="btn btn-success">
                    <span class="glyphicon glyphicon-plus"></span>&nbsp; Add Recipe</button>
            </a>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

mysite/myapp/templates/recipe_form.html
{% extends 'base.html' %}
{% block title %}Add New Recipe{% endblock %}
{% block recipe_active %}active{% endblock %}

{% block body %}

<h1 style="text-align: center">Add New Recipe</h1>
<h2></h2>
<body>
<div class="container-fluid">
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'form_template.html' %}
        <div class="form-group">
            <div class="col-lg-6 col-lg-offset-3 text-center">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>
</div>
</body>
{% endblock %}

mysite/myapp/templates/registration_form.html
{% extends 'base.html' %}
{% block title %}Register{% endblock %}

{% block body %}

<h1 style="text-align: center">Create New Account</h1>
<h2></h2>
<body>
<div class="container-fluid">
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'form_template.html' %}
        <div class="form-group">
            <div class="col-lg-6 col-lg-offset-3 text-center">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>
</div>
</body>
{% endblock %}

mysite/myapp/templates/room.html
{% extends 'base.html' %}

{% block body %}

<!-- chat/templates/chat/room.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
    <textarea id="chat-log" style="color:black" cols="100" rows="20"></textarea><br/>
    <input id="chat-message-input" style="color:black" type="text" size="100"/><br/>
    <input id="chat-message-submit" style="color:black" type="button" value="Send"/>
</body>
<script>
    var roomName = {{ room_name_json }};

    var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/chat/' + roomName + '/');

    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        var message = data['message'];
        document.querySelector('#chat-log').value += (message + '\n');
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        var messageInputDom = document.querySelector('#chat-message-input');
        var message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message
        }));

        messageInputDom.value = '';
    };
</script>
</html>

{% endblock %}

mysite/myapp/templates/test.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}

input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
}

input[type=submit] {
  background-color: #4CAF50;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

.container {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}
</style>
</head>
<body>

<h3>Contact Form</h3>

<div class="container">
  <form action="/action_page.php">
    <label for="fname">First Name</label>
    <input type="text" id="fname" name="firstname" placeholder="Your name..">

    <label for="lname">Last Name</label>
    <input type="text" id="lname" name="lastname" placeholder="Your last name..">

    <label for="country">Country</label>
    <select id="country" name="country">
      <option value="australia">Australia</option>
      <option value="canada">Canada</option>
      <option value="usa">USA</option>
    </select>

    <label for="subject">Subject</label>
    <textarea id="subject" name="subject" placeholder="Write something.." style="height:200px"></textarea>

    <input type="submit" value="Submit">
  </form>
</div>

</body>
</html>